# ============================================================
# EXAMPLE: Copy this file to your repo at
# .github/workflows/weekly-quality.yml
# ============================================================

name: Weekly Quality Check

on:
  schedule:
    - cron: "0 9 * * 1"  # Every Monday 9am UTC
  workflow_dispatch:
    inputs:
      auto_merge_tier:
        description: "1=issues only, 2=PRs only, 3=auto-merge"
        type: choice
        options: ["1", "2", "3"]
        default: "2"

jobs:
  quality:
    # Calls the reusable workflow from claude_experiments
    uses: YOUR_GITHUB_USER/claude_experiments/.github/workflows/weekly-quality-check.yml@master
    with:
      auto_merge_tier: ${{ github.event.inputs.auto_merge_tier || 2 }}
      test_command: "pytest tests/ -x"  # Your test command
      target_branch: "dev"              # Branch to target PRs against
      model: "gpt-5.2"                  # Azure OpenAI model
      analysis_mode: "both"             # upgrade, strategic, or both
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      KEY_VAULT_ENDPOINT: ${{ secrets.KEY_VAULT_ENDPOINT }}


# ============================================================
# SETUP: Add these 4 secrets to your repo (Settings > Secrets):
#
#   AZURE_CLIENT_ID       → Your Azure service principal client ID
#   AZURE_TENANT_ID       → Your Azure tenant ID
#   AZURE_CLIENT_SECRET   → Your Azure service principal secret
#   KEY_VAULT_ENDPOINT    → https://your-keyvault.vault.azure.net/
#
# The action uses these to authenticate to Key Vault, which
# provides the Azure OpenAI API key for GPT-5.2 calls.
# ============================================================
